[package]
name = "hyprAdvanced"
version = "0.1.0"
edition = "2021"

[dependencies]
hyprland = { git = "https://github.com/hyprland-community/hyprland-rs", branch = "master" }
regex = "1.11.0"
crossbeam-channel = "0.5.13"